const mensagens = [
    "Acredite em você mesmo e em todas as suas capacidades.",
    "Hoje é um ótimo dia para começar algo novo!",
    "Você é mais forte do que imagina.",
    "Cada dia é uma nova oportunidade para ser feliz.",
    "Nunca é tarde para ser o que você poderia ter sido.",
    "A felicidade não é algo pronto. Ela vem das suas próprias ações.",
    "Seja a mudança que você deseja ver no mundo.",
    "A vida é 10% o que acontece com você e 90% como você reage a isso.",
    "Não importa a cor do céu. Quem faz o dia bonito é você.",
    "O segredo para ser feliz é aceitar o lugar onde você está hoje na vida e dar o melhor de si todos os dias.",
    "Acredite, você tem forças para chegar onde quiser. Basta querer.",
    "Viva cada momento, ria todos os dias, ame além das palavras.",
    "A felicidade depende mais do estado de espírito do que das circunstâncias externas.",
    "Faça de cada momento um lugar seguro para os seus sonhos.",
    "A maior de todas as conquistas é a conquista de si mesmo.",
    "Siga confiante na direção dos seus sonhos.",
    "A vida é curta, sorria para quem chora, ignore quem te critica e seja feliz com quem se importa com você.",
    "Você é a única pessoa responsável pela sua felicidade.",
    "Sonhe, acredite, dedique-se e realize.",
    "O melhor ainda está por vir.",
    "Acredite: tudo tem um propósito e acontece no momento certo.",
    "Nada é tão nosso quanto os nossos sonhos.",
    "O que você faz hoje pode melhorar todos os seus amanhãs.",
    "Você nunca sabe a força que tem, até que a sua única alternativa é ser forte.",
    "Não desista, alguém está se inspirando em você.",
    "A vida é feita de escolhas. Quando você dá um passo para frente, inevitavelmente alguma coisa fica para trás.",
    "Aceite o que é, esqueça o que foi e tenha fé no que será.",
    "O segredo da felicidade é encontrar a nossa alegria na alegria dos outros.",
    "Felicidade é a combinação de sorte com escolhas bem feitas.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "A persistência é o caminho do êxito.",
    "Só se pode alcançar um grande êxito quando nos mantemos fiéis a nós mesmos.",
    "Ser feliz sem motivo é a mais autêntica forma de felicidade.",
    "A gratidão transforma o que temos em suficiente.",
    "Transforme seu medo em motivação.",
    "O primeiro passo para conseguir algo é desejá-lo.",
    "Ninguém, além de você, está no controle da sua felicidade.",
    "Otimismo é a fé em ação. Nada se pode levar a efeito sem otimismo.",
    "Você é capaz de mais do que imagina.",
    "Acredite nos seus sonhos e eles podem se tornar realidade.",
    "Queira o bem, plante o bem e o resto vem.",
    "A vida é sobre cair sete vezes e se levantar oito.",
    "O que não te desafia, não te transforma.",
    "A sua maior competição é você mesmo.",
    "Aproveite as pequenas coisas, pois um dia você pode olhar para trás e perceber que elas eram grandes coisas.",
    "A vida é curta demais para ser pequena.",
    "Acredite na beleza dos seus sonhos.",
    "A única maneira de fazer um excelente trabalho é amar o que você faz.",
    "Você é incrível do jeito que você é.",
    "Ser feliz é reconhecer que vale a pena viver, apesar de todos os desafios.",
    "O que você pensa, você cria. O que você sente, você atrai. O que você acredita, torna-se realidade.",
    "Seja o motivo pelo qual alguém acredita que a bondade ainda existe.",
    "Nunca pare de sonhar, pois só os sonhos transformam a realidade.",
    "Que a gente nunca desaprenda a recomeçar.",
    "Acredite: coisas boas acontecem para quem espera.",
    "Cada dia é uma chance para ser melhor que ontem.",
    "Que a gente não perca essa estranha mania de ter fé na vida.",
    "Faça mais do que apenas existir, viva.",
    "Não tenha medo de falhar, tenha medo de não tentar.",
    "Não importa o que você decidiu. O que importa é que isso te faça feliz.",
    "Tudo o que um sonho precisa para ser realizado é alguém que acredite que ele possa ser realizado.",
    "O impossível é apenas uma das especialidades de Deus.",
    "A vida começa onde termina a sua zona de conforto.",
    "Acredite em milagres, mas não dependa deles.",
    "Para ter algo que você nunca teve, é preciso fazer algo que você nunca fez.",
    "Os ventos e as ondas estão sempre do lado dos navegadores mais competentes.",
    "Você é do tamanho do seu sonho.",
    "Seja a energia que você quer atrair.",
    "A melhor maneira de prever o futuro é criá-lo.",
    "É a coragem, não a sorte, que determina seu destino.",
    "A vida é uma aventura ousada ou nada.",
    "O que você faz hoje pode mudar todos os seus amanhãs.",
    "Seus sonhos não precisam de plateia, eles só precisam de você.",
    "Você é o escritor da sua própria história.",
    "Nunca é tarde demais para ser o que você poderia ter sido.",
    "Lembre-se que grandes realizações não são feitas por impulso, mas por uma soma de pequenas realizações.",
    "Não espere por uma crise para descobrir o que é importante em sua vida.",
    "Acredite que você pode, assim você já está no meio do caminho.",
    "Tudo vale a pena quando a alma não é pequena.",
    "O sucesso é ir de fracasso em fracasso sem perder o entusiasmo.",
    "Seja feliz com o que você tem, enquanto persegue o que você quer.",
    "A felicidade é um caminho, não um destino.",
    "A chave para a felicidade é sonhar; a chave para o sucesso é tornar os sonhos realidade.",
    "Não existe um caminho para a felicidade. A felicidade é o caminho.",
    "Sua vida é sua mensagem para o mundo. Faça dela uma inspiração.",
    "Tudo o que somos é resultado do que pensamos.",
    "Se você quer que algo aconteça, faça acontecer.",
    "A maior aventura que você pode experimentar é viver a vida dos seus sonhos.",
    "Acredite no poder das suas ações.",
    "Você tem dentro de si, agora, tudo o que precisa para lidar com o que quer que o mundo lhe envie.",
    "A vida é mais do que apenas aumentar sua velocidade.",
    "Cada novo dia é uma nova oportunidade para mudar sua vida.",
    "Lute pelo seu propósito e não pelas suas limitações.",
    "Não coloque limites em seus sonhos, coloque fé.",
    "A vida é sobre criar impacto, não uma renda.",
    "Os melhores sonhos acontecem quando você está acordado.",
    "Viver é a coisa mais rara do mundo. A maioria das pessoas apenas existe.",
    "Seja a versão mais brilhante e vibrante de si mesmo.",
    "A vida é uma oportunidade, aproveite-a."
];

function gerarMensagem() {
    const mensagem = mensagens[Math.floor(Math.random() * mensagens.length)];
    document.getElementById('mensagem').value = mensagem;
}

function limparMensagem() {
    document.getElementById('mensagem').value = '';
}
